### ISSUE TITLE
Stats for DataNodes

### ISSUE THREAD

**Issue by JacksonMaxfield** [quiltdata/quilt#495]
This relates to [#427](https://github.com/quiltdata/quilt/issues/427).

Has there been thought into adding a similar system like mentioned in the above issue but on the DataNode level.

```python
print(pkg.group_node.data_node.inspect())

object_type: file (json)
original_name: 'this_was_a_file.json'
size: 123 MB
default_load: filepath
```

Would allow users that want to view the details of a node without opening it up a method to do so.

**Comment by akarve** [comment]
Yes. File extensions are critical since currently the package interface hides them. We already store `orginal_name` in the package tree so it's straightforward to resurface it. Size also makes sense though that is currently a dynamic server-side attribute. Will need to think about how to surface it statically.
