### ISSUE TITLE
Consolidate API and Python doc files

### ISSUE THREAD

**Issue by akarve** [quiltdata/quilt#630]
Merge docs/api-python.md and docs/api-cli.md with something like https://github.com/GitbookIO/plugin-codetabs

Problem: will not render nicely on GitHub :-/

**Comment by qxf2** [comment]
@akarve, I took a quick look. GitHub markdown does not support code tabs. GitBook produces static HTML pages based on the .md files but those HTML files need to be served using a web server for you to see the code tabs extension.  

![example_gitbook_served](https://user-images.githubusercontent.com/4759449/42446811-42a3c812-8395-11e8-88ea-13e884e37444.png)


I assume you don't want to go down this path. If you do, let me know and I can produce a first version of the documentation using GitBook based on your ./docs/ directory. You can host the files somewhere on Quiltdata.com and simply link it in your ./README.md


In the meanwhile, I can merge the two .md files and probably format them better (haven't tried yet). If you want to go down this path, what would you like the final .md file to be called?

**Comment by akarve** [comment]
@qxf2 thanks for looking into this. i suggest that we close as "won't fix" for the time being. we had a single markdown file in the past, but it proved difficult to maintain. if you find a better solution or format for the API docs, we're open to them. the high-level pattern is that the CLI and Python APIs have about 90% overlap, but different syntax.

**Comment by qxf2** [comment]
@akarve - today I noticed you are already using GitBook and hosting it on https://docs.quiltdata.com. So the first solution I outlined in my previous comment is possible. 

Do your users read the instructions from md files on GitHub or do they consume them from docs.quitltdata? The only complication comes when users read instructions from both your md files on GitHub and docs.quiltdata. In that case, we will have to "won't fix" or have a third file consolidating the two files (I know this is a maintenance headache but maybe worth it for the readability) and display only the consolidated file on docs.quiltdata with code tabs.

The code changes themselves seem simple (add a plugin to book.json, change ./docs/SUMMARY.md to link to a consolidated file with code tabs, create the consolidated file with two code tabs called 'PYTHON' and 'CLI'). Since I am new to GitBook, working on this patch is not a waste of my time.

**Comment by akarve** [comment]
We should maintain legibility of both the GitHub markdown and the gitbook render, as sometimes users necessarily use the raw .md docs, so I think we're in the "won't fix" bucket. Thanks again for the input. Looking forward to your future contributions.
