### ISSUE TITLE
Duplicate node names in directory

### ISSUE THREAD

**Issue by chrisfilo** [quiltdata/quilt#681]
It seems I have some funky names in my dataset

```
Failed to build the package: Duplicate node names in directory '/efs/images/961'. 'S06_shift_1.nii.gz' was renamed to 'S06_shift_1_nii_gz', which overlaps with 'S06_shift_-1.nii.gz'
````

Could there be a better way of escaping "-" than removing it? Or using hashes for ids with names as metadata?

**Comment by akarve** [comment]
It looks like the name mangler (whose job is to produce valid Python identifiers) is dropping `-`, causing a collision. Based on  your example. that can indeed be fixed pretty easily. I will assign this issue.

The long term solution is that version 3 of the API will not mangle names at all since bracket syntax will be the preferred access mechanism.

A workaround is to change the file names to avoid collision (or put them in separate directories). You can also modify package trees by hand with `._set()`.
